groupId=atomic
serverAddress=127.0.0.1:8611
conf=127.0.0.1:8609,127.0.0.1:8610,127.0.0.1:8611
dataPath=./data3/
totalSlots=1
# Max log entries the leader returns per pull request (pull-replication mode), default 25
maxPullLogEntries=25